

//اذاعه

const Chioh = {
  "سهره مع القرأن الكريم": {
    name: "سهره مع القرأن الكريم",
    lison: [
      {
        title: "سهره مع القران الشيخ محمد عبد الوهاب الطنطاوى (سوره الرعد)",
        titleEn: "An evening with the Quran, Sheikh Muhammad Abd al-Wahhab al-Tantawi (Surat al-Ra'd)",
        url: "https://youtu.be/FLo5LxbxNYM?si=RJVNbOJSc5nYi78g",
        duration: "11:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "سهره مع القران الكريم - الشيخ كامل يوسف البهتيمى - سورتى (فصلت -والعلق)",
        titleEn: "An evening with the Holy Quran - Sheikh Kamel Youssef Al-Bahtimi - Surat Fussilat and Al-Alaq",

        url: "https://youtu.be/KI8iZkSIo9g?si=ckaq-T9S5T_N5l9V",
        duration: "15:33",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " سهره مع القران الكريم - الشيخ شعبان الصياد -سورتى (الفرقان والنازعات)",
        titleEn: "Evening with the Holy Quran - Sheikh Shaaban Al-Sayyad - Surat Al-Furqan and An-Nazi'at",
        url: "https://youtu.be/A3aExoA4ZBk?si=Y9O554eTRwlXUv_4",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "سهره مع القران الكريم - الشيخ عبد العزيز على فرج (سوره الكهف)",
        titleEn:"Evening with the Holy Quran - Sheikh Abdul Aziz Ali Farag (Surat Al-Kahf)",
        url: "https://youtu.be/i8aGMydAMR8?si=1R6OfQIMfhBefSW5",
        duration: "15:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " برنامج -سهره مع القران الكريم - الشيخ احمد ابو المعاطى -(سوره مريم)",
        titleEn: "Program - An Evening with the Holy Quran - Sheikh Ahmed Abu Al-Maati - (Surat Maryam)",
        url: "https://youtu.be/3jp_mDrWTiw?si=OGPD-7I2mhD2CqD0",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
     
     
    ],
  },
  "قطوف من حدائق الايمان": {
    name:  "قطوف من حدائق الايمان",
    lison: [
       {
        title: "اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان(1)",
        titleEn: "Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (1)",
        url: "https://youtu.be/RqtAhQ5LjaI?si=qF-DG_SxaKRnnLBX",
        duration: "11:34",
            name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان(2)",
        titleEn:  "Radio of the Holy Quran from Cairo - Program: Selections from the Gardens of Faith (2)",

        url: "https://youtu.be/5id31FgDt90?si=2ez23ACOwZq6vT8b",
        duration: "15:33",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان(3)",

        titleEn: "Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (3)",
        url: "https://youtu.be/1iBraK1Zsls?si=6rjOMt8O1nFUDpmd",
        duration: "12:34",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذاعه القرءان الكريم من القاهره -برنامج قطوغ من حدائق الايمان (4)",
        titleEn:"Radio of the Holy Quran from Cairo - “Qatogh from the Gardens of Faith” program (4)",
        url: "https://youtu.be/KixVNjrsZr4?si=o0ZNZKIiKLPyf-uC",
        duration: "15:20",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان (5)",
        titleEn: "Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (5)",
        url: "https://youtu.be/KwbyOMshlt8?si=g6XmTOpRezJuNdIk",
        duration: "12:34",
         name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان(6)",
        titleEn:"Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (6)",
        url:" https://youtu.be/p-VGwonWWgs?si=yQpyIuxk4GYCgsY7",
        duration: "15:20",
         name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان(7)",
        titleEn: "Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (7)",
        url: "https://youtu.be/iR_UkqEn47o?si=z-tL6cgmK_f1wqYX",
        duration: "12:34",
            name: "المهندس ايمن عبد الرحيم",
      },
           {
        title: "اذاعه القران الكريم من القاهره -برنامج قطوف من حدائق الايمان (8)",
        titleEn: "Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (8)",
        url: "https://youtu.be/oDQoFNHRUiA?si=tT4HVXQOb8rXW85J",
        duration: "11:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذاعه القران الكريم من القاهره - برنامج قطوف من حدائق الايمان (9)",
        titleEn:"Holy Quran Radio from Cairo - “Picks from the Gardens of Faith” Program (9)",
        url: "https://youtu.be/fa7O1B_0PoA?si=k0y1gLdeGnX_Vnz1",
        duration: "1:25:08",
           name: "المهندس ايمن عبد الرحيم",
      },
      
    
    ], 
  },
   "احاديث الدكتور عبد الله شحاته": {
    name:  "الشيخ محمد متولي الشعراوي",
    lison: [
       {
        title: "الفرق بين الشيطان والنفس الاماره بالسوء",
        titleEn: "Are you satisfied to be an ordinary person?",
        url: "https://www.youtube.com/watch?v=66CkZc1O_fE&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "11:34",
               name: "الشيخ محمد متولي الشعراوي",
      },
         {
        title: "لقاء الرسول مع الجن",
        titleEn: "Are you satisfied to be an ordinary person?",
        url: "https://www.youtube.com/watch?v=ryYLH_tl2B0&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "11:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "ما الحكمه من البلاء",
        titleEn: "Change your outlook on life",

        url: "https://www.youtube.com/watch?v=ZOK2UOG5bik&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:33",
              name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " احداث فلسطين",
        titleEn: "How to turn from disobedience to obedience",
        url: "https://www.youtube.com/watch?v=ZCXIlTqVkJM&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "خطب الشيخ الشعراوى",
        titleEn:"If worship is too heavy for you",
        url:" https://www.youtube.com/watch?v=rbWQW4xzSFw&t=17s&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "قصه زى القرنين",
        titleEn: "How to become special",
        url: "https://www.youtube.com/watch?v=WPUIRHsXHvE&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " من هوا الخضر",
        titleEn:"The difference between love and admiration",
        url: "https://www.youtube.com/watch?v=Vfnyi1iCEW0&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:20",
          name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "تعلم كيف يأتيك الرزق",
        titleEn: "Why do you feel that prayer, remembrance and reading the Quran are heavy on your tongue?",
        url: "https://www.youtube.com/watch?v=_Ye3-b9Sb2E&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
              name: "الشيخ محمد متولي الشعراوي",
      },
           {
        title: "علاقه الجن بالانسان",
        titleEn: "Why did the occupation not change the language of the Egyptian people?",
        url: "https://www.youtube.com/watch?v=RLh86mRYmX4&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "11:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "الفرق بين معصيه ادم وابليس",
        titleEn:"How to deal with your desires",
        url: "https://www.youtube.com/watch?v=oF7XKxsQ-ko&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "1:25:08",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "كبف بدء الخلق",
        titleEn: "The best people after the messengers and prophets",
        url: "https://www.youtube.com/watch?v=_8CbTfJDYgM&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK0gcJCa0JAYcqIYzv",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "اليقين بالله",
        titleEn:"Engagement rules",
        url: "https://www.youtube.com/watch?v=m_QVUriK4As&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "14:20",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " سبب شراءهم ليوسف بثمن بخث",
        titleEn:"Facing laziness in performing acts of worship",
        url: "https://www.youtube.com/watch?v=WuZKuXh_cpI&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
         name: "الشيخ محمد متولي الشعراوي",
      },
      {
  title:"قصه الاسراء والمعراج",
        titleEn:"Marriage at puberty or at a later age?",
        url: "https://www.youtube.com/watch?v=0xwKbbn2-8Q&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " قصه داود عليه السلام",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=1Q7q-sn0uFA&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK0gcJCa0JAYcqIYzv",
        duration: "12:34",
          name: "الشيخ محمد متولي الشعراوي",
      },
       {
        title: " قصه اصحاب الكهف",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=E3fYfZMMsNc&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
   {
        title: " لماذا نزل القرءان عربيا",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=kYaFq_5FTdE&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " قصه بقره بنى اسرائيل",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=WBwCUpGFNu4&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
      //سلسه
        {
        title: "تفسير سوره الكهف",
        titleEn: "Interpretation of Surat Al-Kahf",
        url: "https://www.youtube.com/live/Qwi-57eKNnE?si=wPCZFJVQWX3Fd9gA",
        duration: "11:34",
               name: "الشيخ محمد متولي الشعراوي",
      },
         {
        title: "سلسله مختارات الشعراوى",
        titleEn: "Al-Shaarawy Selections Series",
        url: "https://youtube.com/playlist?list=PLjdstnTfkW8h4SQGIp5DMOl7-Yg1TUV82&si=jCJvXUCGjwJMxEuM",
        duration: "11:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "سلسله عن فوائد الصيام",
        titleEn: "A series on the benefits of fasting",

        url: "https://youtube.com/playlist?list=PLjdstnTfkW8h99BpsC3PH9s8Ys1qqeZZ8&si=ZEXL_JS9fxtVAyMZ",
        duration: "15:33",
              name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " سلسله تفسير سوره يس",
        titleEn: "Interpretation of Surah Yasin series",
        url: "https://youtube.com/playlist?list=PLjdstnTfkW8h99BpsC3PH9s8Ys1qqeZZ8&si=ZEXL_JS9fxtVAyMZ",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "سلسله تفسير سوره النحل",
        titleEn:"Series of interpretation of Surat An-Nahl",
        url:" https://youtube.com/playlist?list=PLjdstnTfkW8iq6Sk0zkE96ykK2n9NqkRn&si=8QG5XtqQK-M1ZuJQ",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "متى تكون ليله القدر",
        titleEn: "When is the Night of Decree?",
        url: "https://youtu.be/IFAlngPvd6o?si=nF0boZrlsQDOFomH",
        duration: "12:34",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " قصه سيدنا يوسف",
        titleEn:"The story of our master Joseph",
        url: "https://youtu.be/dx2uyM2EwrE?si=wc370pXq6-RSMv4n",
        duration: "15:20",
          name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "ذكر مصر فى القرءان الكريم",
        titleEn: "Egypt mentioned in the Holy Quran",
        url: "https://youtu.be/RrmfZ0qNqEk?si=uqoLV5W2kmpHf9_c",
        duration: "12:34",
              name: "الشيخ محمد متولي الشعراوي",
      },
           {
        title: "كيف يخسر الانسان نعم الله عليه",
        titleEn: "How can a person lose God's blessings upon him?",
        url: "https://youtu.be/ur7nXkuX30E?si=qiyZV61yqVi8TcKr",
        duration: "11:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "اسباب تأثير هجره الرسول على المستقبل الاسلامى",
        titleEn:"Reasons for the impact of the Prophet’s migration on the Islamic future",
        url: "https://youtu.be/9aCvYQePkx4?si=u1sNuBCPxpOGyrFq",
        duration: "1:25:08",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "هجره الرسول",
        titleEn: "The Prophet's migration",
        url: "https://youtu.be/ffuDSuTyU-I?si=3xOeEfAbvKj6igdt",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "لماذ اختار الرسول الهجره الى الحبشه",
        titleEn:"Why did the Messenger choose to migrate to Abyssinia?",
        url: "https://youtu.be/CyAGllCoYnc?si=ZeB0r5IJZuSQeqn2",
        duration: "14:20",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "عقوق الوالدين",
        titleEn:"disobedience to parents",
        url: "https://youtu.be/fyD9ACNP-Ew?si=7jrS3xab3U8_R-iW",
        duration: "12:34",
         name: "الشيخ محمد متولي الشعراوي",
      },
      {
  title:"ضرب الرجل لزوجته",
        titleEn:"Man beats his wife",
        url: "https://youtu.be/qKCp5iuTn8U?si=3Yms-GvM7yOBnmpx",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " الزنى",
        titleEn: "Adultery",
        url: "https://youtu.be/v127wH5uAGY?si=9-UwqWCkUl0U_kqR",
        duration: "12:34",
          name: "الشيخ محمد متولي الشعراوي",
      },
       {
        title: " اسرار العلاقه الزوجيه الناجحه",
        titleEn: "Adultery Secrets of a Successful Marital Relationship",
        url: "https://youtu.be/19ABTSzrxvU?si=Qb4zkbqXrhr1qbQe",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
   {
        title: " الصبر والصيام",
        titleEn: "Patience and fasting",
        url: "https://youtu.be/arNYJUGdjIg?si=z_MTHylkw5Px0Xb2",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " الدليل على وقوع الوحى",
        titleEn: "Evidence of the occurrence of revelation",
        url: "https://youtu.be/oM1vyCOEZe0?si=S2UXIiMRRZih0QDP",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },

          {
        title: " اسرار العلاقه الزوجيه الناجحه",
        titleEn: "Secrets of a successful marital relationship",
        url: "https://youtu.be/19ABTSzrxvU?si=Qb4zkbqXrhr1qbQe",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
   {
        title: " المحرمات",
        titleEn: "taboo",
        url: "https://youtu.be/W0DUr8N67xw?si=TUHH3GXq8rJpCoXm",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " سلسله قصص الانبياء",
        titleEn: "Stories of the Prophets Series",
        url: "https://youtu.be/TTTOrFgODAs?si=Op1iJK86c8jJT2ch",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " سلسله تفسير القران كامل",
        titleEn: "A complete series of interpretations of the Qur’an",
        url: "https://youtube.com/playlist?list=PLjdstnTfkW8iG1T1TGVffBRIa4WFMy6zl&si=XVu9uJy44wH08B1H",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
  ]},
}
export default Chioh