

 const Chioh ={
  "الدحيح": {
    name: "الشيخ سمير مصطفي",
    lison: [
      {
        title: "ارهقتنى زنوبى ما هوا الحل",
        titleEn: "Zenobia has exhausted me and I am back. What is the solution?",
        url: "https://www.youtube.com/watch?v=LxSwWwBCuHY&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "11:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "اصلاح القلب للتقريب الى الله",
        titleEn: "Reforming the heart to get closer to God",

        url: "https://www.youtube.com/watch?v=wWzy8my9B30&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "15:33",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " صفات اهل الجنه",
        titleEn: "Characteristics of the people of Paradise",
        url: "https://www.youtube.com/watch?v=qREf_Kwl0V4&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "رقق قلبك",
        titleEn:"Soften your heart",
        url: "https://www.youtube.com/watch?v=-r3yRMPtlxY&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "15:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " تدبير الله عز وجل للعبد",
        titleEn: "God Almighty's plan for the servant",
        url: "https://www.youtube.com/watch?v=XHghGZL5YWo&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " رحله ابن القيم فى طلب العلم",
        titleEn:"Ibn al-Qayyim's journey in search of knowledge",
        url: "https://www.youtube.com/watch?v=bxzIFf9WLXw&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "15:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " الانس بالله",
        titleEn: "Live with God",
        url: "https://www.youtube.com/watch?v=wmd2NXngXmk&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
           {
        title: "السر الذى جعلنى استقيم على العباده",
        titleEn: "The secret that made me stick to worship",
        url: "https://www.youtube.com/watch?v=LFhjxQtvSbg&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "11:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "مشاهد من يوم القيامه",
        titleEn:"Scenes from the Day of Judgment",
        url: "https://www.youtube.com/watch?v=c8Seo9zDfjY&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "1:25:08",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "الاشارات التى يرسلها الله اليك",
        titleEn: "Signs God is sending you",
        url: "https://www.youtube.com/watch?v=U0eU4lTphjM&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "سرعه اللجاء الى الله",
        titleEn:"Quickly resort to God",
        url: "https://www.youtube.com/watch?v=mp3YQL66RuQ&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "14:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " ومن يدبر الامر",
        titleEn:" Who manages the matter?",
        url: "https://www.youtube.com/watch?v=KOigux0Tgpk&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " حقيقه الرضا ومن اين ينشاء",
        titleEn:"The reality of satisfaction and where it comes from",
        url: "https://www.youtube.com/watch?v=evns7VTPj-U&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "15:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " شخصيه سيدنا الفاروق عمر رضى الله عنه",
        titleEn: "The personality of our master Al-Farouq Omar, may God be pleased with him",
        url: "https://www.youtube.com/watch?v=mJ69a1uWtMk&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      //DODD
          {
        title: "الاستقامه وعلاج نقص العهد مع الله",
        titleEn: "Righteousness and treatment of broken covenant with God",
        url: "https://www.youtube.com/watch?v=CCuKs79dSHk&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ0gcJCa0JAYcqIYzv",
        duration: "11:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "من صور اليقين فالله عز وجل",
        titleEn:'One of the images of certainty is God Almighty.',
        url: "https://www.youtube.com/watch?v=7SDQd3eB1Ak&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "14:33",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "الصدق فى اراده التوبه",
        titleEn: "Honesty in the will to repent",
        url:" https://www.youtube.com/watch?v=vE_E3IC61Go&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "رقه قلب رسول الله",
        titleEn: "The tenderness of the heart of the Messenger of God",
        url:"https://www.youtube.com/watch?v=ckwgfZjkkJw&t=19s&pp=ygUf2LHZgtipINmC2YTYqCDYsdiz2YjZhCDYp9mE2YTZhw%3D%3D",
        duration: "6:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " الخشوع",
        titleEn: "Humility",
        url: "https://www.youtube.com/watch?v=acbkxJ0U76I&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " تعظيم شان الصلاه",
        titleEn:"Magnifying the status of prayer",
        url: "https://www.youtube.com/watch?v=UFh502bTxNg&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "15:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " الاجابه على الاسئله",
        titleEn: "answer the questions",
        url: "https://www.youtube.com/watch?v=WPDXwm9ntK4&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
           {
        title: "مقاطع مؤثره",
        titleEn: "Influential clips",
        url: "https://www.youtube.com/watch?v=NDJrIg3UEjQ&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "11:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "تذكر الموت",
        titleEn:"Remember death",
        url: "https://www.youtube.com/watch?v=7EUBi5xNz8E&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "1:25:08",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "كلام عن الكعبه المكرمه",
        titleEn: "Talk about the Holy Kaaba",
        url: "https://www.youtube.com/watch?v=CTcpjKLQXN8&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "النجاشى ملك الحبشه",
        titleEn:"Negus, King of Abyssinia",
        url: "https://www.youtube.com/watch?v=7CsKcluYA4Y&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "14:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " رحله الروح بعد الموت",
        titleEn: "The journey of the soul after death",
        url: "https://www.youtube.com/watch?v=b72J8X0ryFA&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " سبب عدم التوفيق",
        titleEn:"The reason for the failure",
        url: "https://www.youtube.com/watch?v=pOS7BeContQ&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "4:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " المحافظه على الوقت",
        titleEn: "Save time",
        url: "https://www.youtube.com/watch?v=RxOr02DL8Ss&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ",
        duration: "1:27:34",
          name: "الشيخ سمير مصطفي",
      },
        {
        title: " فهم اسماء الله وصفاته",
        titleEn: "Understanding the names and attributes of God",
        url: "https://www.youtube.com/watch?v=Y2eWUFWrazo&pp=ygUe2KfZhNi02YrYriDYs9mF2YrYsSDZhdi12LfZgdmJ0gcJCa0JAYcqIYzv",
        duration: "10:34",
          name: "الشيخ سمير مصطفي",
      },
      // سلسلات
        {
        title: "سلسله السيره النبويه",
        titleEn:"Series of the Prophet's Biography",
        url: "https://youtube.com/playlist?list=PL6C03BCFE87398A78&si=ZN3E69Q0rtXwEAlq",
        duration: "14:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " سلسه عقائد البلاد",
        titleEn: "Series of country beliefs",
        url: "https://youtube.com/playlist?list=PLSUcSqxe9RhwgiU3RCyePYbf3sUwLgpXc&si=SLA5YFNWt414cagy",
        duration: "12:34",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: " سلسه القضاء والقدر",
        titleEn:"The chain of fate and destiny",
        url: "https://youtube.com/playlist?list=PLSUcSqxe9RhyS7_hi2I5D7CH2sACsPjFW&si=0QHfDX_Md3bK2f-H",
        duration: "4:20",
          name: "الشيخ سمير مصطفي",
      },
      {
        title: "سلسه المعارك الكبرى",
        titleEn: "The Great Battles Series",
        url: "https://youtube.com/playlist?list=PL09AC5B8EC7B3803A&si=0GiWxGT-yr8bddsB",
        duration: "1:27:34",
          name: "الشيخ سمير مصطفي",
      },
     
    ],
  },
  "المهندس ايمن عبد الرحيم": {
    name: "المهندس ايمن عبد الرحيم",
    lison: [
       {
        title: "ترضى تكون انسان عادى",
        titleEn: "Are you satisfied to be an ordinary person?",
        url: "https://www.youtube.com/watch?v=fIHUry17r3o&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "11:34",
            name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "تغيير نظرتك عن الحياه",
        titleEn: "Change your outlook on life",

        url: "https://www.youtube.com/watch?v=ZXWzWWXzPmU&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "15:33",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " كيف تتحول من المعصيه الى الطاعه",
        titleEn: "How to turn from disobedience to obedience",
        url: "https://www.youtube.com/watch?v=tlNcdOGU7Es&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "اذا ثقلت عليك العباده",
        titleEn:"If worship is too heavy for you",
        url: "https://www.youtube.com/watch?v=kjvlUhlQLcc&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "15:20",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "كبف تصبح مميز",
        titleEn: "How to become special",
        url: "https://www.youtube.com/watch?v=LkNl6ULOUDs&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
         name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " الفرق بين الحب والاعجاب",
        titleEn:"The difference between love and admiration",
        url: "https://www.youtube.com/watch?v=GxPDmN5GoAE&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "15:20",
         name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " لماذا تشعر ان الصلاه والذكر وقراءه القرءان ثقيل على لسانك",
        titleEn: "Why do you feel that prayer, remembrance and reading the Quran are heavy on your tongue?",
        url: "https://www.youtube.com/watch?v=NSOmckOvkGw&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
            name: "المهندس ايمن عبد الرحيم",
      },
           {
        title: "لماذا لم يغير الحتلال لغه الشعب المصرى",
        titleEn: "Why did the occupation not change the language of the Egyptian people?",
        url: "https://www.youtube.com/watch?v=9METth6J9z0&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "11:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "كيف تتعامل مع رغباتك",
        titleEn:"How to deal with your desires",
        url: "https://www.youtube.com/watch?v=lQiaUWNxmkA&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "1:25:08",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "افضل الناس بعد الرسل والانبياء",
        titleEn: "The best people after the messengers and prophets",
        url: "https://www.youtube.com/watch?v=8g40BGQP6KI&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "ضوابط الخطوبه",
        titleEn:"Engagement rules",
        url: "https://www.youtube.com/watch?v=Z3Yf1PPGLVM&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "14:20",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " مواجه كسل القيام بالعبادات",
        titleEn:"Facing laziness in performing acts of worship",
        url: "https://www.youtube.com/watch?v=uCpgtlr5uZc&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " الزاج فى سن البلوغ ام فى سن متأخر",
        titleEn:"Marriage at puberty or at a later age?",
        url: "https://www.youtube.com/watch?v=z2NS2QiZCBE&t=125s&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "15:20",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " فما ظنكم برب العالمين",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=Kj17OWBVW04&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      //DODD
          {
        title: "الفرق بين الاحتلال البريطانى والاحتلال الفرنسى",
        titleEn: "The difference between the British occupation and the French occupation",
        url: "https://www.youtube.com/watch?v=Mv5ZmSAD2TQ&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "11:34",
        name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "ايه الى وصلنا لكده",
        titleEn:'How did we get to this point?',
        url: "https://www.youtube.com/watch?v=-3Oz1wglubc&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "14:33",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "كيف تتعلم اى لغه بسهوله",
        titleEn: "How to learn any language easily",
        url:" https://www.youtube.com/watch?v=D-3ggRprKWs&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
       name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "هل الشريعه الاسلاميه تناسب هذا العصر",
        titleEn: "Is Islamic law suitable for this era?",
        url:"https://www.youtube.com/watch?v=S0P-c7NOZ0Y&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "6:20",
            name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " تكرار الالفاظ يؤثر على الاخلاق",
        titleEn: "Repetition of words affects morals",
        url: "https://www.youtube.com/watch?v=GXZ--PLIy9w&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " مشكله العلمانيه مع الاسلام",
        titleEn:"The problem of secularism with Islam",
        url: "https://www.youtube.com/watch?v=eR7L44ppfuQ&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "15:20",
            name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " الحب والاعجاب",
        titleEn: "Love and admiration",
        url: "https://www.youtube.com/watch?v=7s7N21CraLw&pp=ygUb2KfZitmF2YYg2LnYqNiv2KfZhNix2K3ZitmF",
        duration: "12:34",
        name: "المهندس ايمن عبد الرحيم",
      },
      //سلاسل
       {
        title: "السلسله التاريخيه كامله",
        titleEn:"The complete historical series",
        url: "https://youtube.com/playlist?list=PLEZsPMnigpwlLvZ828A5-QIrA61oE_PSb&si=5wkMdPy4a_2LfLK3",
        duration: "1:25:08",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "كيف يسود المسلومون العالم",
        titleEn: "How Muslims rule the world",
        url: "https://youtu.be/oZyeeBFMdD0?si=fU07y6Xwh2eGSYe_",
        duration: "12:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "ماذا يريد الزوجان من بعضهم",
        titleEn:"What do spouses want from each other?",
        url: "https://youtu.be/NSOmckOvkGw?si=B19qkiXokiFXkWMk",
        duration: "14:20",
           name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " سلسله بره الصندوق",
        titleEn:"Out of the Box series",
        url: "https://youtube.com/playlist?list=PL9saDKf7tQ7vRKXzW0Rlaa8WFLqUTNI34&si=ICVi7SygWGa8zyCY",
        duration: "12:34",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " سلسله بيت المسلم",
        titleEn:"Muslim House Series",
        url: "https://youtube.com/playlist?list=PLnFJTGgdQYTOWcUXdFLzpsgy6_rlXkwrh&si=ics8nC2X1fG5QbxL",
        duration: "15:20",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " سلسله دوره الوعى اللغوى",
        titleEn: "Linguistic awareness course series",
        url: "https://youtube.com/playlist?list=PL9hkk6GeaGBd4bcCSyv3K6gQognxGbrtZ&si=zB0CVeiUyXEQQKmb",
        duration: "12:34",
          name: "المهندس ايمن عبد الرحيم",
      },
   
          {
        title: "سلسله الخلفاء الراشدين",
        titleEn: "The Rightly Guided Caliphs Series",
        url: "https://youtube.com/playlist?list=PLlZMehTwxvLjy9EUhsuBrqF-8Hy7FFPeV&si=dC4DbsWulAw5jA3u",
        duration: "11:34",
        name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "سلسله لدراسه التاريخ الاسلامى",
        titleEn:'A series for the study of Islamic history',
        url: "https://youtube.com/playlist?list=PLviw8YquvTid6cAJP-qeqb0PSJ9l0LpSX&si=cVBVH5MRwz632qcj",
        duration: "14:33",
          name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "سلسله البيت المسلم",
        titleEn: "Muslim House Series",
        url:" https://youtube.com/playlist?list=PLnFJTGgdQYTOWcUXdFLzpsgy6_rlXkwrh&si=XUoxa_CSHt1TdqZq",
        duration: "12:34",
       name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: "السيره النبويه",
        titleEn: "The Prophet's Biography",
        url:"https://youtube.com/playlist?list=PLHj9AP66UerES26GFSJTaLGJmPNY-qDE9&si=c78UrgfpYadCxAzl",
        duration: "6:20",
            name: "المهندس ايمن عبد الرحيم",
      },
      {
        title: " سلسله تأسيس ووعى المسلم المعاصر",
        titleEn: "The Foundation and Awareness of the Contemporary Muslim series",
        url: "https://youtube.com/playlist?list=PLnFJTGgdQYTNJLSn8ENSzD9qaPz3LypyW&si=72Lc-RimQmvx2kGR",
        duration: "12:34",
           name: "المهندس ايمن عبد الرحيم",
      },

    
    ], 
  },
   "الشيخ محمد متولي الشعراوي": {
    name: "الشيخ محمد متولي الشعراوي",
    lison: [
       {
        title: "الفرق بين الشيطان والنفس الاماره بالسوء",
        titleEn: "Are you satisfied to be an ordinary person?",
        url: "https://www.youtube.com/watch?v=66CkZc1O_fE&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "11:34",
               name: "الشيخ محمد متولي الشعراوي",
      },
         {
        title: "لقاء الرسول مع الجن",
        titleEn: "Are you satisfied to be an ordinary person?",
        url: "https://www.youtube.com/watch?v=ryYLH_tl2B0&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "11:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "ما الحكمه من البلاء",
        titleEn: "Change your outlook on life",

        url: "https://www.youtube.com/watch?v=ZOK2UOG5bik&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:33",
              name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " احداث فلسطين",
        titleEn: "How to turn from disobedience to obedience",
        url: "https://www.youtube.com/watch?v=ZCXIlTqVkJM&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "خطب الشيخ الشعراوى",
        titleEn:"If worship is too heavy for you",
        url:" https://www.youtube.com/watch?v=rbWQW4xzSFw&t=17s&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "قصه زى القرنين",
        titleEn: "How to become special",
        url: "https://www.youtube.com/watch?v=WPUIRHsXHvE&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " من هوا الخضر",
        titleEn:"The difference between love and admiration",
        url: "https://www.youtube.com/watch?v=Vfnyi1iCEW0&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:20",
          name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "تعلم كيف يأتيك الرزق",
        titleEn: "Why do you feel that prayer, remembrance and reading the Quran are heavy on your tongue?",
        url: "https://www.youtube.com/watch?v=_Ye3-b9Sb2E&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
              name: "الشيخ محمد متولي الشعراوي",
      },
           {
        title: "علاقه الجن بالانسان",
        titleEn: "Why did the occupation not change the language of the Egyptian people?",
        url: "https://www.youtube.com/watch?v=RLh86mRYmX4&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "11:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "الفرق بين معصيه ادم وابليس",
        titleEn:"How to deal with your desires",
        url: "https://www.youtube.com/watch?v=oF7XKxsQ-ko&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "1:25:08",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "كبف بدء الخلق",
        titleEn: "The best people after the messengers and prophets",
        url: "https://www.youtube.com/watch?v=_8CbTfJDYgM&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK0gcJCa0JAYcqIYzv",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "اليقين بالله",
        titleEn:"Engagement rules",
        url: "https://www.youtube.com/watch?v=m_QVUriK4As&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "14:20",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " سبب شراءهم ليوسف بثمن بخث",
        titleEn:"Facing laziness in performing acts of worship",
        url: "https://www.youtube.com/watch?v=WuZKuXh_cpI&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
         name: "الشيخ محمد متولي الشعراوي",
      },
      {
  title:"قصه الاسراء والمعراج",
        titleEn:"Marriage at puberty or at a later age?",
        url: "https://www.youtube.com/watch?v=0xwKbbn2-8Q&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " قصه داود عليه السلام",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=1Q7q-sn0uFA&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK0gcJCa0JAYcqIYzv",
        duration: "12:34",
          name: "الشيخ محمد متولي الشعراوي",
      },
       {
        title: " قصه اصحاب الكهف",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=E3fYfZMMsNc&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
   {
        title: " لماذا نزل القرءان عربيا",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=kYaFq_5FTdE&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " قصه بقره بنى اسرائيل",
        titleEn: "What do you think of the Lord of the Worlds?",
        url: "https://www.youtube.com/watch?v=WBwCUpGFNu4&pp=ygUk2YXYrdmF2K8g2YXYqtmI2YTZiiDYp9mE2LTYudix2KfZiNmK",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
      //سلسه
        {
        title: "تفسير سوره الكهف",
        titleEn: "Interpretation of Surat Al-Kahf",
        url: "https://www.youtube.com/live/Qwi-57eKNnE?si=wPCZFJVQWX3Fd9gA",
        duration: "11:34",
               name: "الشيخ محمد متولي الشعراوي",
      },
         {
        title: "سلسله مختارات الشعراوى",
        titleEn: "Al-Shaarawy Selections Series",
        url: "https://youtube.com/playlist?list=PLjdstnTfkW8h4SQGIp5DMOl7-Yg1TUV82&si=jCJvXUCGjwJMxEuM",
        duration: "11:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "سلسله عن فوائد الصيام",
        titleEn: "A series on the benefits of fasting",

        url: "https://youtube.com/playlist?list=PLjdstnTfkW8h99BpsC3PH9s8Ys1qqeZZ8&si=ZEXL_JS9fxtVAyMZ",
        duration: "15:33",
              name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " سلسله تفسير سوره يس",
        titleEn: "Interpretation of Surah Yasin series",
        url: "https://youtube.com/playlist?list=PLjdstnTfkW8h99BpsC3PH9s8Ys1qqeZZ8&si=ZEXL_JS9fxtVAyMZ",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "سلسله تفسير سوره النحل",
        titleEn:"Series of interpretation of Surat An-Nahl",
        url:" https://youtube.com/playlist?list=PLjdstnTfkW8iq6Sk0zkE96ykK2n9NqkRn&si=8QG5XtqQK-M1ZuJQ",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "متى تكون ليله القدر",
        titleEn: "When is the Night of Decree?",
        url: "https://youtu.be/IFAlngPvd6o?si=nF0boZrlsQDOFomH",
        duration: "12:34",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " قصه سيدنا يوسف",
        titleEn:"The story of our master Joseph",
        url: "https://youtu.be/dx2uyM2EwrE?si=wc370pXq6-RSMv4n",
        duration: "15:20",
          name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "ذكر مصر فى القرءان الكريم",
        titleEn: "Egypt mentioned in the Holy Quran",
        url: "https://youtu.be/RrmfZ0qNqEk?si=uqoLV5W2kmpHf9_c",
        duration: "12:34",
              name: "الشيخ محمد متولي الشعراوي",
      },
           {
        title: "كيف يخسر الانسان نعم الله عليه",
        titleEn: "How can a person lose God's blessings upon him?",
        url: "https://youtu.be/ur7nXkuX30E?si=qiyZV61yqVi8TcKr",
        duration: "11:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "اسباب تأثير هجره الرسول على المستقبل الاسلامى",
        titleEn:"Reasons for the impact of the Prophet’s migration on the Islamic future",
        url: "https://youtu.be/9aCvYQePkx4?si=u1sNuBCPxpOGyrFq",
        duration: "1:25:08",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "هجره الرسول",
        titleEn: "The Prophet's migration",
        url: "https://youtu.be/ffuDSuTyU-I?si=3xOeEfAbvKj6igdt",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "لماذ اختار الرسول الهجره الى الحبشه",
        titleEn:"Why did the Messenger choose to migrate to Abyssinia?",
        url: "https://youtu.be/CyAGllCoYnc?si=ZeB0r5IJZuSQeqn2",
        duration: "14:20",
        name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: "عقوق الوالدين",
        titleEn:"disobedience to parents",
        url: "https://youtu.be/fyD9ACNP-Ew?si=7jrS3xab3U8_R-iW",
        duration: "12:34",
         name: "الشيخ محمد متولي الشعراوي",
      },
      {
  title:"ضرب الرجل لزوجته",
        titleEn:"Man beats his wife",
        url: "https://youtu.be/qKCp5iuTn8U?si=3Yms-GvM7yOBnmpx",
        duration: "15:20",
            name: "الشيخ محمد متولي الشعراوي",
      },
      {
        title: " الزنى",
        titleEn: "Adultery",
        url: "https://youtu.be/v127wH5uAGY?si=9-UwqWCkUl0U_kqR",
        duration: "12:34",
          name: "الشيخ محمد متولي الشعراوي",
      },
       {
        title: " اسرار العلاقه الزوجيه الناجحه",
        titleEn: "Adultery Secrets of a Successful Marital Relationship",
        url: "https://youtu.be/19ABTSzrxvU?si=Qb4zkbqXrhr1qbQe",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
   {
        title: " الصبر والصيام",
        titleEn: "Patience and fasting",
        url: "https://youtu.be/arNYJUGdjIg?si=z_MTHylkw5Px0Xb2",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " الدليل على وقوع الوحى",
        titleEn: "Evidence of the occurrence of revelation",
        url: "https://youtu.be/oM1vyCOEZe0?si=S2UXIiMRRZih0QDP",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },

          {
        title: " اسرار العلاقه الزوجيه الناجحه",
        titleEn: "Secrets of a successful marital relationship",
        url: "https://youtu.be/19ABTSzrxvU?si=Qb4zkbqXrhr1qbQe",
        duration: "12:34",
            name: "الشيخ محمد متولي الشعراوي",
      },
   {
        title: " المحرمات",
        titleEn: "taboo",
        url: "https://youtu.be/W0DUr8N67xw?si=TUHH3GXq8rJpCoXm",
        duration: "12:34",
           name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " سلسله قصص الانبياء",
        titleEn: "Stories of the Prophets Series",
        url: "https://youtu.be/TTTOrFgODAs?si=Op1iJK86c8jJT2ch",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
        {
        title: " سلسله تفسير القران كامل",
        titleEn: "A complete series of interpretations of the Qur’an",
        url: "https://youtube.com/playlist?list=PLjdstnTfkW8iG1T1TGVffBRIa4WFMy6zl&si=XVu9uJy44wH08B1H",
        duration: "12:34",
             name: "الشيخ محمد متولي الشعراوي",
      },
  ]},
}





export default Chioh;